name: learn-github-actions
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
run-name: ${{ github.actor }} is learning GitHub Actions


jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo "test"
