name: echo-on-push
on:
  workflow_dispatch:
  push:
    branches:
    - main
run-name: ${{ github.actor }} is pushing a new file


jobs:
  print_on_push:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
