name: learn-github-actions
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
run-name: ${{ github.actor }} is learning GitHub Actions


jobs:
  echo:
    runs-on: echo "test"
    
